# Generated by Django 3.2 on 2023-03-07 19:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='noimage.webp', max_length=255, verbose_name='image'),
        ),
    ]
