# Generated by Django 3.2 on 2023-03-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_multi_colour',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_one_colour',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
