# Generated by Django 3.2 on 2023-03-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_multi_colour',
            new_name='has_colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_one_colour',
        ),
    ]
