# Generated by Django 3.2 on 2023-03-27 22:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='content',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='title',
        ),
        migrations.AddField(
            model_name='productreview',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 27, 22, 58, 12, 281111, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
