# Generated by Django 3.2 on 2023-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customise',
            field=models.BooleanField(default=False),
        ),
    ]
