# Generated by Django 3.2 on 2023-04-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_customise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customise',
        ),
    ]
